# Generated by Django 4.1.3 on 2022-12-06 15:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electronico')),
                ('asunto', models.CharField(max_length=100, verbose_name='Motivo de Contacto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('no_casa', models.CharField(max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='twitter')),
                ('instagram', models.URLField(verbose_name='instagram')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usario registrado')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electronico')),
                ('passw', models.CharField(max_length=60)),
                ('passwConfirmacion', models.CharField(max_length=60)),
                ('estatus', models.BooleanField(default=False, verbose_name='Activo / Inactivo')),
                ('tipo', models.IntegerField(default=0, verbose_name='Admin / visitante')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('imagen_perfil', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros', models.TextField(verbose_name='Nosotros')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo Electronico')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('teaser', models.CharField(max_length=511, verbose_name='Resumen')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(max_length=255, upload_to='categoria/', verbose_name='Imagen')),
                ('estatus', models.BooleanField(default=False, verbose_name='Publicado / No publicado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True, verbose_name='Fecha de modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, null=True, verbose_name='Fecha de eliminacion')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.categoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255, verbose_name='Nombres')),
                ('estatus', models.BooleanField(default=False, verbose_name='Publicado / No publicado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True, verbose_name='Fecha de modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, null=True, verbose_name='Fecha de eliminacion')),
                ('noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.noticia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.usuario')),
            ],
        ),
    ]
