# Generated by Django 4.1.4 on 2022-12-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.CharField(max_length=511, verbose_name='Resumen'),
        ),
    ]
