# Generated by Django 4.0.6 on 2022-12-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_noticia_contenido'),
        ('webapp', '0005_auto_20221211_2120'),
    ]

    operations = [
    ]
